#: The following is ignored by Kitty, but picked up by vim/Neovim
#:
#: fileencoding=utf-8 — treats the file as UTF-8.
#: foldmethod=marker — enables manual code folding using markers such as:
#
#: Font {{{ some code... }}}
#:
#: Place cursor in section and enter "za"
#:
# vim:fileencoding=utf-8:foldmethod=marker

################ Imports ################

include conf/tab-bar.conf
include conf/cursor.conf

################ General ################

background_opacity 0.7
background_blur 16

hide_window_decorations titlebar-only

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

window_padding_width 1 8 1 8

allow_remote_control yes
macos_option_as_alt yes

############## Key Bindings ##############

# Option + Left/Right: send Alt+Left/Right to Neovim
map alt+left send_text all \x1b[1;3D
map alt+right send_text all \x1b[1;3C

# Option + Delete: delete previous word
# This sends Ctrl-W, which Neovim insert mode already uses for delete word
map alt+backspace send_text all \x17

# Command + Left/Right: send Ctrl+Left/Right to Neovim
map cmd+left  send_text all \x1b[1;5D
map cmd+right send_text all \x1b[1;5C

# Command + Up/Down: top/bottom of file
map cmd+up   send_text all \x1b[1;5H
map cmd+down send_text all \x1b[1;5F

# Command + Delete: delete to beginning of line
# This sends Ctrl-U, which Neovim insert mode already uses for delete to start of line
map cmd+backspace send_text all \x15

# Shift + Arrow: select by character/line
map shift+left  send_text all \x1b[1;2D
map shift+right send_text all \x1b[1;2C

# Option + Shift + Left/Right: select by word
map alt+shift+left  send_text all \x1b[1;4D
map alt+shift+right send_text all \x1b[1;4C

# Command + Shift + Left/Right: select to start/end of line
map cmd+shift+left  send_text all \x1b[1;10D
map cmd+shift+right send_text all \x1b[1;10C
