# Use ~/.config/kitty/tab_bar.py
tab_bar_style custom

# Only display the tab bar when at least two tabs exist
tab_bar_min_tabs 2

# Place the tab bar at the top
tab_bar_edge top

# Padding
tab_bar_margin_height 10 0

# Entire tab bar background
tab_bar_background #1e1e2e
# tab_bar_margin_color #1e1e2e

# Give every tab the same background
active_tab_background #1e1e2e
inactive_tab_background #1e1e2e

# Indicate the active tab using only its text color
active_tab_foreground #cba6f7
inactive_tab_foreground #7f849c

# Prevent bold or italic styling from being another active indicator
active_tab_font_style normal
inactive_tab_font_style normal

# Display only the tab title
tab_title_template "{title}"
active_tab_title_template "{title}"
